export type RuntimeStressVerdict =
  | 'STRESS_PASSED'
  | 'STRESS_REVIEW'
  | 'STRESS_FAILED'
  | 'BLOCKED';

export type RuntimeStressScenario =
  | 'HEAP_PRESSURE'
  | 'EVENT_LOOP_LAG'
  | 'OCR_BURST'
  | 'REPLAY_FLOOD'
  | 'SNAPSHOT_CHURN'
  | 'GC_STORM';

export interface RuntimeStressSample {
  readonly scenario: RuntimeStressScenario;
  readonly iterations: number;
  readonly heapDeltaBytes: number;
  readonly maxLatencyMs: number;
  readonly rejectedEvents: number;
  readonly blockedEvents: number;
}

export interface RuntimeStressPolicy {
  readonly maxIterations: number;
  readonly maxHeapDeltaBytes: number;
  readonly maxLatencyMs: number;
  readonly maxRejectedEvents: number;
  readonly maxBlockedEvents: number;
}

export interface RuntimeStressReport {
  readonly verdict: RuntimeStressVerdict;
  readonly samples: readonly RuntimeStressSample[];
  readonly totalIterations: number;
  readonly maxHeapDeltaBytes: number;
  readonly maxLatencyMs: number;
  readonly rejectedEvents: number;
  readonly blockedEvents: number;
  readonly reason: string;
}

/**
 * Deterministic institutional stress harness.
 *
 * This engine does not allocate artificial memory or attack the device.
 * It classifies compact stress samples generated by controlled tests.
 *
 * Complexity:
 * - Time: O(n), where n is the number of stress samples.
 * - Space: O(1) for aggregation.
 */
export class RuntimeStressHarness {
  public constructor(
    private readonly policy: RuntimeStressPolicy = {
      maxIterations: 10000,
      maxHeapDeltaBytes: 12 * 1024 * 1024,
      maxLatencyMs: 500,
      maxRejectedEvents: 100,
      maxBlockedEvents: 50,
    },
  ) {}

  public evaluate(samples: readonly RuntimeStressSample[]): RuntimeStressReport {
    if (samples.length === 0) {
      return {
        verdict: 'BLOCKED',
        samples,
        totalIterations: 0,
        maxHeapDeltaBytes: 0,
        maxLatencyMs: 0,
        rejectedEvents: 0,
        blockedEvents: 0,
        reason: 'no stress samples available',
      };
    }

    let totalIterations = 0;
    let maxHeapDeltaBytes = 0;
    let maxLatencyMs = 0;
    let rejectedEvents = 0;
    let blockedEvents = 0;

    for (const sample of samples) {
      totalIterations += sample.iterations;
      maxHeapDeltaBytes = Math.max(maxHeapDeltaBytes, sample.heapDeltaBytes);
      maxLatencyMs = Math.max(maxLatencyMs, sample.maxLatencyMs);
      rejectedEvents += sample.rejectedEvents;
      blockedEvents += sample.blockedEvents;
    }

    const verdict = this.resolveVerdict(
      totalIterations,
      maxHeapDeltaBytes,
      maxLatencyMs,
      rejectedEvents,
      blockedEvents,
    );

    return {
      verdict,
      samples,
      totalIterations,
      maxHeapDeltaBytes,
      maxLatencyMs,
      rejectedEvents,
      blockedEvents,
      reason: this.resolveReason(verdict),
    };
  }

  private resolveVerdict(
    totalIterations: number,
    maxHeapDeltaBytes: number,
    maxLatencyMs: number,
    rejectedEvents: number,
    blockedEvents: number,
  ): RuntimeStressVerdict {
    if (
      totalIterations > this.policy.maxIterations ||
      maxHeapDeltaBytes > this.policy.maxHeapDeltaBytes ||
      maxLatencyMs > this.policy.maxLatencyMs * 2 ||
      blockedEvents > this.policy.maxBlockedEvents * 2
    ) {
      return 'STRESS_FAILED';
    }

    if (
      maxLatencyMs > this.policy.maxLatencyMs ||
      rejectedEvents > this.policy.maxRejectedEvents ||
      blockedEvents > this.policy.maxBlockedEvents
    ) {
      return 'STRESS_REVIEW';
    }

    return 'STRESS_PASSED';
  }

  private resolveReason(verdict: RuntimeStressVerdict): string {
    if (verdict === 'STRESS_FAILED') {
      return 'runtime failed institutional stress policy';
    }

    if (verdict === 'STRESS_REVIEW') {
      return 'runtime requires review after stress degradation';
    }

    if (verdict === 'BLOCKED') {
      return 'stress harness blocked execution';
    }

    return 'runtime remained within institutional stress policy';
  }
}
